### ISSUE TITLE
"Generated Password"responsive hk.

### ISSUE THREAD

**Issue by mertmtn** [mustafakaracuha/UIDesignDay7-password-generator#1]
Ekteki görseldeki gibi şifre, arayüzden sonra kesilmiş görünüyor. Length arttıkça responsive özelliği azalıyor, input alanını genişletebilirsin.

![image](https://user-images.githubusercontent.com/37337606/186254064-73531133-2eb0-4c76-b0f4-8cfe52e427ba.png)

**Comment by mustafakaracuha** [comment]
İlgileniyorum teşekkürler
